# Dockerfile.cvserver
FROM python:3.11-slim

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libgl1-mesa-glx libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

COPY server/requirements_cv.txt requirements.txt
RUN pip install -r requirements.txt

COPY server/ ./server/

EXPOSE 8200
CMD ["uvicorn", "cv_server:app", "--host", "0.0.0.0", "--port", "8200"]