apiVersion: v1
kind: Secret
metadata:
  name: aidi-secrets
  namespace: aidi
type: Opaque
data:
  langfuse-public-key: sk-lf-eeb6301f-da91-4f03-9cb5-eddef48abf4d
  langfuse-secret-key: sk-lf-eeb6301f-da91-4f03-9cb5-eddef48abf4d